package Model;
// Generated 25/10/2020 08:59:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.metamodel.relational.ForeignKey;

/**
 * Cliente generated by hbm2java
 */

public class Cliente  implements java.io.Serializable {

    
 
    private Integer idCliente;
     private String nombre;
     private Long telefono;
     private String direccion;
     private String email;
     private Date registro;

     private Set ventas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String nombre, Long telefono, String direccion, String email, Date registro, Set ventas) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.registro = registro;
       this.ventas = ventas;
    }
   
    
    
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Date registro) {
        this.registro = registro;
    }
    
    
    public Set getVentas() {
        return this.ventas;
    }
    
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
        //ventas.add(this.ventas);        
    }




}


