package Model;
// Generated 25/10/2020 08:59:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */


public class Empleado  implements java.io.Serializable {

 
 
//    @Column(name = "idEmpleado")
     private Integer idEmpleado;
     private String nombreEmpleado;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String puesto;
     private Double salario;
     private Date horaEntrada;
     private Date horaSalida;
     private Long telefonoEmpleado;
     private String emailEmpleado;         

     private Set ventas = new HashSet(0);

    public Empleado() {
    }

    public Empleado(String nombreEmpleado, String apellidoPaterno, String apellidoMaterno, String puesto, Double salario, Date horaEntrada, Date horaSalida, Long telefonoEmpleado, String emailEmpleado, Set ventas) {
       this.nombreEmpleado = nombreEmpleado;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.puesto = puesto;
       this.salario = salario;
       this.horaEntrada = horaEntrada;
       this.horaSalida = horaSalida;
       this.telefonoEmpleado = telefonoEmpleado;
       this.emailEmpleado = emailEmpleado;
       this.ventas = ventas;
    }
   
        
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
  
    
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Date getHoraEntrada() {
        return this.horaEntrada;
    }
    
    public void setHoraEntrada(Date horaEntrada) {
        this.horaEntrada = horaEntrada;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Long getTelefonoEmpleado() {
        return this.telefonoEmpleado;
    }
    
    public void setTelefonoEmpleado(Long telefonoEmpleado) {
        this.telefonoEmpleado = telefonoEmpleado;
    }
    public String getEmailEmpleado() {
        return this.emailEmpleado;
    }
    
    public void setEmailEmpleado(String emailEmpleado) {
        this.emailEmpleado = emailEmpleado;
    }
    
    
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
        //ventas.add(this.ventas);        
    }




}


