package Model;
// Generated 25/10/2020 08:59:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombreProducto;
     private Integer existencia;
     private Double precio;
     private Set ventaproductos = new HashSet(0);

    public Producto() {
    }

    public Producto(String nombreProducto, Integer existencia, Double precio, Set ventaproductos) {
       this.nombreProducto = nombreProducto;
       this.existencia = existencia;
       this.precio = precio;
       this.ventaproductos = ventaproductos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public Integer getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getVentaproductos() {
        return this.ventaproductos;
    }
    
    public void setVentaproductos(Set ventaproductos) {
        this.ventaproductos = ventaproductos;
    }




}


