package Model;
// Generated 25/10/2020 08:59:31 PM by Hibernate Tools 4.3.1



/**
 * Ventaproducto generated by hbm2java
 */
public class Ventaproducto  implements java.io.Serializable {


     private Integer idVentaproducto;
     private Producto producto;
     private Venta venta;
     private Double precioVentaproducto;

    public Ventaproducto() {
    }

    public Ventaproducto(Producto producto, Venta venta, Double precioVentaproducto) {
       this.producto = producto;
       this.venta = venta;
       this.precioVentaproducto = precioVentaproducto;
    }
   
    public Integer getIdVentaproducto() {
        return this.idVentaproducto;
    }
    
    public void setIdVentaproducto(Integer idVentaproducto) {
        this.idVentaproducto = idVentaproducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Double getPrecioVentaproducto() {
        return this.precioVentaproducto;
    }
    
    public void setPrecioVentaproducto(Double precioVentaproducto) {
        this.precioVentaproducto = precioVentaproducto;
    }




}


