package Model;
// Generated 25/10/2020 08:59:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ConstraintMode;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.ws.rs.ConstrainedTo;
import org.hibernate.annotations.IndexColumn;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;


/**
 * Venta generated by hbm2java
 */
//@Entity
//@Table(name = "venta")
public class Venta  implements java.io.Serializable {
    
    
    
//    @Id
//    @GeneratedValue
//    @Column(name = "idVenta")
     private Integer idVenta;    
     private Date fecha;
     private Date horaVenta;
     private Double montoTotal;
     private Empleado empleado; 
     private Cliente cliente;                     
     private Set ventaproductos = new HashSet(0);

    public Venta() {
    }

    public Venta(Date fecha, Date horaVenta, Double montoTotal, Empleado empleado, Cliente cliente, Set ventaproductos) {                     
                     
       this.fecha = fecha;
       this.horaVenta = horaVenta;
       this.montoTotal = montoTotal;
       this.empleado = empleado;
       this.cliente = cliente;            
       this.ventaproductos = ventaproductos;
       
    }
   
    
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    
    
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;        
    }
    
    
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;        
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHoraVenta() {
        return this.horaVenta;
    }
    
    public void setHoraVenta(Date horaVenta) {
        this.horaVenta = horaVenta;
    }
    public Double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Set getVentaproductos() {
        return this.ventaproductos;
    }
    
    public void setVentaproductos(Set ventaproductos) {
        this.ventaproductos = ventaproductos;                
    }




}


